name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          API_KEY_QUOTES: ${{ secrets.API_KEY_QUOTES }}
          API_KEY_CUTOFF: ${{ secrets.API_KEY_CUTOFF }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: CollegeSearch.apk
          # A file, directory or wildcard pattern that describes what to upload
          path: app/build/outputs/apk/debug/app-debug.apk